### ISSUE TITLE
Add requirements.txt file

### ISSUE THREAD

**Issue by nagracks** [Aareon/J-Discord#25]
Using `pip freeze > requirements.txt`. It will list all project dependencies
with their version number, I'm assuming you're using virtulenv.

**Comment by Aareon** [comment]
I am not currently using virtualenv, and the source here is outdated. The finished product is only intended to be used on one machine. The updated source is closed.

**Comment by nagracks** [comment]
You should use virtualenv, there is no reason not to use it.
